Completed hw4
imOnVacation/Fall22---Full-Stack-Homework pull request #5
Opened 2022-11-06 00:29 UTC by imOnVacation

2022-11-08 06:48 UTC, sashetov approved these changes
looks good to merge. I had one small comment regarding parseInt, so if you think I'm correct there maybe remove that but its good to merge otherwise

2022-11-08 06:48 UTC, sashetov commented on hw4/01-routing.js
> +})
looks good

2022-11-08 06:48 UTC, sashetov commented on hw4/02-sessions.js
> +})
also looks good

2022-11-08 06:48 UTC, sashetov commented on hw4/03-form.js
> +    if (!userLetter) letterOut = 'No, thank you'
ok looks correct

2022-11-08 06:48 UTC, sashetov commented on hw4/04-templates.js
> +        const mapAsc = new Map([...map.entries()].sort())
nice use of Map

2022-11-08 06:48 UTC, sashetov commented on hw4/04-templates.js
> +    const nf = new Intl.NumberFormat('en-US')
good solution for number format

2022-11-08 06:48 UTC, sashetov commented on hw4/04-templates.js
> +            if (parseInt(pop, 10) >= 50000000) {
i don't think you need to parseInt here as its already a Number but lmk if I'm incorrect

2022-11-08 06:48 UTC, sashetov commented on hw4/04-templates.js
> +        const mapAsc = new Map([...map.entries()].sort((a, b) => b[1] - a[1]))
nice use of sort and map

2022-11-08 06:48 UTC, sashetov commented on hw4/04-templates.js
> +})
again, looks good and good use of map

2022-11-08 23:00 UTC, imOnVacation commented on hw4/04-templates.js
> +            if (parseInt(pop, 10) >= 50000000) {
Hey, you are right! Thanks for catching that, I have removed parseInt.

2022-11-09 08:50 UTC, ethanSE requested changes
I think that there was a confusion here about the note suggesting using map. She is referring to Array.prototype.map unfortunately and not Map. It is confusing that these have a similar name. 

Array.prototype.map
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map
Map
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

There's not really any reason to use a Map here and it adds a bit of complexity. If you're not familiar with Array.prototype.map it is definitely worth getting familiar with as it is both very useful and expected knowledge for any work involving javascript.

2022-11-09 08:50 UTC, ethanSE commented on hw4/04-templates.js
> +    // map the output array to create an array with country names and capitals
I believe that this note means to use Array.prototype.map not Map.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

To go from an Array of country objects to an array of formatted strings.

2022-11-09 08:52 UTC, ethanSE commented on hw4/04-templates.js
> +    // map the output array to create an array with country names and capitals
I've added this as a change request

2022-11-15 19:50 UTC, JeremyIV commented
Everything looks good, nice job!

2022-11-16 04:59 UTC, merged